package exception;
/*
 * try 用来检测异常
 * catch 捕获异常
 * finally 释放资源
 */

public class Demo2_Exception {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

	}

}
